import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { ChatbotService, ChatMessage } from '../../services/chatbot.service';
import { AnalyticsService } from '../../services/analytics.service';
import { AccessibilityService } from '../../services/accessibility.service';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatBadgeModule } from '@angular/material/badge';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { ResponsiveTesterComponent } from '../responsive-tester/responsive-tester.component';

@Component({
  selector: 'app-chatbot',
  standalone: true,  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatButtonModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatCardModule,
    MatBadgeModule,
    MatTooltipModule,
    MatDialogModule
  ],
  templateUrl: './chatbot.component.html',
  styleUrl: './chatbot.component.scss'
})
export class ChatbotComponent implements OnInit {
  @ViewChild('chatMessages') chatMessagesElement!: ElementRef;

  private requestSequence = 0;
  private activeRequestId: string | null = null;
  private streamingMessageIndex: number | null = null;

  messages: ChatMessage[] = [];
  messageInput = new FormControl('', [Validators.required, Validators.maxLength(500)]);
  isChatOpen = false;
  isProcessing = false;
  modelStatus = '';
  hasUnreadMessages = false;
  unreadCount = 0;

  constructor(
    private chatbotService: ChatbotService,
    private analyticsService: AnalyticsService,
    private accessibilityService: AccessibilityService,
    private dialog: MatDialog
  ) {
    this.chatbotService.modelStatus$.subscribe(status => this.modelStatus = status);
    this.chatbotService.generatedText$.subscribe(({ requestId, text }) => {
      if (requestId !== this.activeRequestId || !text) {
        return;
      }

      if (this.streamingMessageIndex === null) {
        this.streamingMessageIndex = this.messages.length;
        this.messages.push({ content: text, sender: 'bot', timestamp: new Date() });
      } else {
        const streamedMessage = this.messages[this.streamingMessageIndex];
        this.messages[this.streamingMessageIndex] = { ...streamedMessage, content: streamedMessage.content + text };
      }
      this.scrollToBottom();
    });
  }

  ngOnInit(): void {
    // Load saved messages from local storage
    this.loadChatHistory();

    if (this.messages.length === 0) {
      this.addBotMessage(`Hi there! I'm Patrick's virtual assistant. Ask about his experience, skills, projects, education, or contact information. Replies are generated by AI and grounded in the website.`);
    }
  }
  toggleChat(): void {
    this.isChatOpen = !this.isChatOpen;

    // Reset unread count when opening chat
    if (this.isChatOpen) {
      this.hasUnreadMessages = false;
      this.unreadCount = 0;

      // Announce for screen readers
      const message = 'Chat window opened';
      this.announceToScreenReader(message);
    } else {
      // Stop any ongoing speech when closing the chat
      this.accessibilityService.stopSpeaking();

      // Announce for screen readers
      const message = 'Chat window closed';
      this.announceToScreenReader(message);
    }
  }

  // Helper method for screen reader announcements
  private announceToScreenReader(message: string): void {
    const announcement = document.createElement('div');
    announcement.setAttribute('aria-live', 'assertive');
    announcement.setAttribute('role', 'status');
    announcement.classList.add('sr-only');
    announcement.textContent = message;

    document.body.appendChild(announcement);

    setTimeout(() => {
      document.body.removeChild(announcement);
    }, 1000);
  }  askSuggestedQuestion(question: string, event?: MouseEvent): void {
    // Prevent default click behavior if event is provided
    if (event) {
      event.preventDefault();
      event.stopPropagation();
    }

    this.submitMessage(question);
  }

  sendMessage(event: Event): void {
    // Prevent form submission which would cause page reload
    event.preventDefault();

    if (this.messageInput.invalid || this.isProcessing) {
      return;
    }

    const userMessage = this.messageInput.value || '';

    this.messageInput.reset();
    this.submitMessage(userMessage);
  }

  private submitMessage(userMessage: string): void {
    if (this.isProcessing) {
      return;
    }

    this.addUserMessage(userMessage);
    this.isProcessing = true;
    this.modelStatus = 'Checking portfolio and connecting to AI...';

    const startTime = new Date().getTime();
    const conversation = this.messages.slice(0, -1);
    const requestId = `chat-${Date.now()}-${++this.requestSequence}`;
    this.activeRequestId = requestId;
    this.streamingMessageIndex = null;
    this.chatbotService.processMessage(userMessage, conversation, requestId).subscribe({
      next: response => {
        const responseTime = new Date().getTime() - startTime;
        if (this.streamingMessageIndex === null) {
          this.addMessage(response);
        } else {
          this.messages[this.streamingMessageIndex] = response;
          this.accessibilityService.speak(response.content);
          this.saveChatHistory();
        }
        this.isProcessing = false;
        this.activeRequestId = null;
        this.streamingMessageIndex = null;
        this.analyticsService.trackInteraction(userMessage, responseTime);

        if (!this.isChatOpen) {
          this.hasUnreadMessages = true;
          this.unreadCount++;
        }
        this.saveChatHistory();
      },
      error: error => {
        this.isProcessing = false;
        this.activeRequestId = null;
        this.modelStatus = '';
        const errorMessage = error instanceof Error ? error.message : 'The AI assistant is unavailable. Please try again later.';
        if (this.streamingMessageIndex === null) {
          this.addBotMessage(errorMessage);
        } else {
          this.messages[this.streamingMessageIndex] = {
            content: `${errorMessage} The response was interrupted. Please try again.`,
            sender: 'bot',
            timestamp: new Date()
          };
          this.streamingMessageIndex = null;
          this.saveChatHistory();
        }
      }
    });
  }

  private addUserMessage(content: string): void {
    this.addMessage({
      content,
      sender: 'user',
      timestamp: new Date()
    });
  }

  private addBotMessage(content: string): void {
    this.addMessage({
      content,
      sender: 'bot',
      timestamp: new Date()
    });

    // Mark as unread if chat is closed
    if (!this.isChatOpen) {
      this.hasUnreadMessages = true;
      this.unreadCount++;
    }

    // Save chat history
    this.saveChatHistory();
  }  private addMessage(message: ChatMessage): void {
    this.messages.push(message);

    // Save to local storage
    this.saveChatHistory();

    // If text-to-speech is enabled, read bot messages aloud
    if (message.sender === 'bot') {
      this.accessibilityService.speak(message.content);
    }

    setTimeout(() => this.scrollToBottom(), 100);
  }

  private scrollToBottom(): void {
    if (this.chatMessagesElement) {
      const element = this.chatMessagesElement.nativeElement;
      element.scrollTop = element.scrollHeight;
    }
  }

  // Save chat history to local storage
  private saveChatHistory(): void {
    try {
      const chatHistory = this.messages.map(msg => ({
        ...msg,
        timestamp: msg.timestamp.toString() // Convert Date to string for storage
      }));
      localStorage.setItem('patrick-portfolio-chat', JSON.stringify(chatHistory));
    } catch (error) {
      console.error('Failed to save chat history:', error);
    }
  }

  // Load chat history from local storage
  private loadChatHistory(): void {
    try {
      const savedChat = localStorage.getItem('patrick-portfolio-chat');
      if (savedChat) {
        const chatHistory = JSON.parse(savedChat);
        this.messages = chatHistory.map((msg: any) => {
          const content = String(msg.content || '');
          const plainContent = content.includes('suggested-questions')
            ? 'You can ask about Patrick\'s experience, skills, projects, education, or certifications.'
            : content.replace(/<br\s*\/?>/gi, '\n')
              .replace(/<[^>]*>/g, '')
              .replace(/&nbsp;/g, ' ')
              .replace(/&amp;/g, '&')
              .replace(/&lt;/g, '<')
              .replace(/&gt;/g, '>');

          return {
            ...msg,
            content: plainContent,
            timestamp: new Date(msg.timestamp)
          };
        });

        // Schedule scroll to bottom after view is initialized
        setTimeout(() => this.scrollToBottom(), 200);
      }
    } catch (error) {
      console.error('Failed to load chat history:', error);
      this.messages = [];
    }
  }

  // Clear chat history
  clearChatHistory(): void {
    this.messages = [];
    localStorage.removeItem('patrick-portfolio-chat');

    // Add initial greeting message
    this.addBotMessage(`Hi there! 👋 I've cleared our previous conversation. What would you like to know about Patrick?`);
  }

  // Open responsive design tester
  openResponsiveTester(): void {
    this.dialog.open(ResponsiveTesterComponent, {
      maxWidth: '90vw',
      maxHeight: '90vh',
      width: '90vw',
      height: '90vh',
      panelClass: 'responsive-tester-dialog',
    });
  }
}
